name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: clone
      run: git clone "https://github.com/nsetzer/daedalus.git" daedalus

    - name: configure
      run: ./configure

    - name: run the site build
      run: |
        source venv/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        make build
